name = "leetcode-tracker"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Database bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "leetcode-tracker-db"
database_id = "your-d1-database-id"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "leetcode-tracker-db"
database_id = "your-d1-database-id"

# KV bindings for sessions
[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"

[[env.preview.kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"

# Environment variables
[env.production.vars]
NODE_ENV = "production"
SESSION_SECRET = "your-production-session-secret"

[env.preview.vars]
NODE_ENV = "preview"
SESSION_SECRET = "your-preview-session-secret"

