name = "leetcode-tracker"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:pages"

[env.production]
name = "leetcode-tracker-prod"

[env.staging]
name = "leetcode-tracker-staging"

# Database bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "leetcode-tracker-db"
database_id = "your-d1-database-id"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "leetcode-tracker-staging-db"
database_id = "your-staging-d1-database-id"

# KV bindings for sessions
[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "your-staging-kv-namespace-id"
preview_id = "your-staging-preview-kv-namespace-id"

# Environment variables
[env.production.vars]
NODE_ENV = "production"
SESSION_SECRET = "your-production-session-secret"

[env.staging.vars]
NODE_ENV = "staging"
SESSION_SECRET = "your-staging-session-secret"

# Build configuration
[build]
command = "npm run build:cloudflare"